targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          include:
            - lib/*/*.dart
      isar_generator:
        generate_for:
          include:
            - lib/model/*.dart
